import { appTitle } from "./app.js";
document.title = appTitle;
const chapters = [
  "Introduction",
  "Why should I learn JavaScript?",
  "What is JavaScript? What can we do with it?",
  "How to make a web application dynamic? Front-end, Back-end, Full-stack",
  "JavaScript Engine",
  "Interview Questions Chapter 1 to 4",
  "Install Visual Studio Code",
  "First JavaScript Program",
  "Understand console.log()",
  "Specifications / Documentation",
  "alert()",
  "Overview of Data Types",
  "Program on strings Strings(Single, double, backticks)",
  "Variables, Keywords, Identifiers",
  "let, var, const",
  "Statements, expressions and literals",
  "Why is JavaScript single threaded? Synchronous and Asynchronous programming",
  "Comments",
  "Overview of 8 Data types",
  "Definition of JavaScript",
  "Interview questions from chapter 7 to chapter 18",
  "prompt",
  "Type conversions",
  "Operators",
  "Comparisons",
  "if (conditional statement)",
  "Suresh techs hospital",
  "Free bus pass",
  "confirm",
  "Logical operators",
  "Interview questions from 20 to 29 chapters",
  "Agile-Scrum-Sprint-Daily call",
  "Overview of functions, execution contexts",
  "Scopes",
  "Hoisting",
  "Recap of chapters 32, 33, 34 + Window",
  "Objects - part-1",
  "Objects - part-2 - dot, square brackets, function/method?",
  "Objects - part-3 - copy by value/copy by reference",
  "Objects - part-4 - Object.assign(), spread operators",
  "Objects - part-5 - Deep cloning",
  "Objects - part-6",
  "Objects - part-7 - Keys, values, entries",
  "Objects - part-8 - Property flags, freeze(), seal, preventExtensions",
  "Objects - part-9 - Prototypal inheritance, Object.create()",
  "Objects - part-10 - Symbols",
  "Objects - part-11 - in, hasOwnProperty",
  "Objects - part-12 - for in loop",
  "Objects - part-13 - Interview questions, property shadowing",
  "Arrays - Overview",
  "Arrays - push, pop, shift, unshift",
  "Overview of 50 chapters, What next?",
  "Overview of HTML & CSS",
  "Suresh Biodata - Project",
  "Practice session - 1 - Nenu JavaScript nerchukuntunnanu",
  "Functions in detail - parameters, arguments, rest parameter, difference between spread/rest",
  "Functions - Why functions are called objects? First-class citizens?",
  "Functions - Callbacks?",
  "Practice session - 2 - Counter application",
  "JavaScript Runtime - Call stack, event queue, microtask queue, event loop",
  "Lottery game – part 1 - Math.random(), Math.floor()",
  "Arrays - forEach, map, reduce",
  "Lottery game – part 2 - Dynamically create lottery boxes",
  "setTimeout, setInterval",
  "Lottery game – part 3 - Add an intense feel to the game along with sounds",
  "Online shopping app – part 1",
  "Destructuring – Object, Array",
  "Online shopping app – part 2",
  "find, findIndex, some, every",
  "Arrow functions in short",
  "Online shopping app – part 3",
  "Online shopping app – part 4",
  "filter",
  "Slice and splice",
  "Online shopping app – part 5",
  "Online shopping app – part 6",
  "Sort",
  "Online shopping app – part 7",
  "Deploy our lottery game",
  "Deploy online shopping application - Continuous deployment",
  "Final Project - Demo",
  "Final Project - Part 1",
  "Final Project - Part 2",
  "Modules - import / export",
  "Final Project - Part 3",
  "Final words",
];

const chaptersContainer = document.getElementById("chaptersContainer");

chapters.forEach((chapter) => {
  const listItem = document.createElement("li");
  listItem.textContent = chapter;
  listItem.classList.add("font20px");
  listItem.classList.add("whiteText");
  listItem.classList.add("margin10px");
  chaptersContainer.appendChild(listItem);
});
